# Generated by Django 5.1.2 on 2025-05-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_ratecount_profile_servicecount"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="notifications",
            field=models.TextField(blank=True, null=True),
        ),
    ]
