# Generated by Django 5.1.2 on 2025-05-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_history_profile_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="Rate",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
