# Generated by Django 5.1.2 on 2025-05-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_notification_user_id_delete_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="deliveryCount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="fiveStar",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="scheduleCount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
