# Generated by Django 5.1.2 on 2025-03-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="type_of_schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "daily"),
                    ("weekly", "weekly"),
                    ("monthly", "monthly"),
                    ("Parcel Delivery", "Parcel Delivery"),
                    ("custom", "custom"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
