# Generated by Django 5.1.2 on 2025-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_alter_schedule_type_of_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
