# Generated by Django 5.0.4 on 2025-04-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedule_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type_of_schedule',
            field=models.CharField(blank=True, choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('Parcel Delivery', 'Parcel Delivery'), ('Courier', 'Courier'), ('Pharmacy', 'Pharmacy'), ('custom', 'custom')], max_length=20, null=True),
        ),
    ]
